- name: "Terraform learn"
  hosts: terraform_ansible

  tasks:
    
    - name: Install django deps
      apt:
        pkg:
          - python3
          - virtualenv

        update_cache: yes
      become: yes

    - name: Setup Django
      pip:
        virtualenv: /home/ubuntu/venv
        name:
          - django
          - djangorestframework

    - name: Project Startup
      shell: |
        . /home/ubuntu/venv/activate
        django-admin startproject coffee_pot .

    - name: Start server
      shell: |
        cd /home/ubuntu
        . venv/bin/activate
        nohup python manage.py runserver 0.0.0.0:8000 &

