- name: "Terraform learn"
  hosts: terraform_ansible

  tasks:
    
    - name: Install django deps
      apt:
        pkg:
          - python3
          - virtualenv

        update_cache: yes
      become: yes

    - name: Setup Django
      pip:
        virtualenv: /home/ubuntu/venv
        name:
          - django
          - djangorestframework

    - name: Project Startup
      shell: |
        cd /home/ubuntu

        . /home/ubuntu/venv/bin/activate

        django-admin startproject coffee_pot .
      ignore_errors: true

    - name: Update allowed hosts
      lineinfile:
        path: /home/ubuntu/coffee_pot/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes

    - name: Start server
      shell: |
        cd /home/ubuntu
        . venv/bin/activate
        nohup python manage.py runserver 0.0.0.0:8000 &

